version: "3.9"

services:
  db:
    image: postgres
    build: .
    volumes:
      - ./data/db:/var/lib/postgresql/data
  web:
    build: .
    env_file:
      - ./env.database
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=postgres
      - USE_DOCKER=yes
      - DJANGO_DEBUG=True
      - DATABASE_URL=postgres://django:1001032661@127.0.0.1:5432/test_django
    depends_on:
      - db

  pycharm:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
    volumes:
      - .:/app
    links:
        - db