# Generated by Django 4.0 on 2021-12-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_mananager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date'),
        ),
        migrations.AddField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Expiration Date'),
        ),
    ]
