# Generated by Django 4.0 on 2021-12-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_mananager', '0002_product_date_created_product_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(auto_now=True, verbose_name='Expiration Date'),
        ),
    ]
