# Generated by Django 4.0 on 2021-12-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_mananager', '0003_alter_product_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(default='DEFAULT VALUE', null=True, verbose_name='Expiration Date'),
        ),
    ]
