# Generated by Django 4.0 on 2021-12-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_mananager', '0004_alter_product_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='document',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
