# Generated by Django 4.0 on 2021-12-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_mananager', '0005_alter_client_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
